### PR TITLE
subnet/config.go: Fix handling of subnet config

### LINKED ISSUE #696: flannel doesn't error early enough when configured with a bad subnet
Seen on flannel v0.7.1

Using this config:
```
➜  ~ etcdctl set /coreos.com/network/config '{
                                          "Network": "10.0.0.0/32",
                                          "Backend": {
                                            "Type": "alloc"          
                                          }
                                        }'
```

I see
```
I0427 16:38:16.995413    9492 main.go:241] Found network config - Backend type: alloc
I0427 16:38:17.002158    9492 local_manager.go:181] Picking subnet in range 10.0.0.0 ... 10.0.0.1
I0427 16:38:17.003740    9492 local_manager.go:167] Allocated lease (10.0.0.0/33) to current node (192.168.10.218) 
I0427 16:38:17.003949    9492 main.go:196] Wrote subnet file to /run/flannel/subnet.env
I0427 16:38:17.003975    9492 main.go:201] Finished starting backend.
E0427 16:38:17.008344    9492 watch.go:171] Subnet watch failed: failed to parse subnet key /coreos.com/network/subnets/10.0.0.0-33
```
Which isn't great behavior

I think that it shouldn't allocate a /33 (?1?!) lease and it should probably just exit

### PR DESCRIPTION
**Pull request by tomdee**
Fix all the limits, especially around minimum sizes

Fixes #696

### CODE REVIEW

File: subnet/config.go [hunk 1]
```diff
@@ -53,16 +53,28 @@ func ParseConfig(s string) (*Config, error) {
...
+		// the first subnet isn't used, so splitting into two one only provide one usable host.
+		if cfg.SubnetLen < cfg.Network.PrefixLen+2 {
+			return nil, errors.New("Network must be able to accommodate at least four subnets")
 		}
 	} else {
-		// try to give each host a /24 but if the whole network
-		// is /24 or smaller, half the network
+		// try to give each host a /24 but if the whole network is /24 or smaller, split the network into four.
+		// the first subnet isn't used, so splitting into two one only provide one usable host.
 		if cfg.Network.PrefixLen < 24 {
```
Comment (gunjan5) [inline subnet/config.go]: shouldn't this be `<=` according to the comment?

Comment (tomdee) [reply subnet/config.go]: @gunjan5 I updated the comments and code on these lines. PTAL.
