### PR TITLE
Fix seg fault when aws subnet linked to main route table

### LINKED ISSUE #256: (aws-vpc) panic if subnet using Main route table
In an AWS VPC all subnets use the Main route table by default, unless explicitly associated to another route table.

A panic occurs if the instance flannel is running on is inside a subnet which was not explicitly associated to a route table:

```
systemd[1]: Starting Network fabric for containers...
etcdctl[2605]: {"Network": "172.17.0.0/16", "Backend": {"Type": "aws-vpc"}}
sdnotify-proxy[2609]: I0717 12:26:17.685499 00001 main.go:275] Installing signal handlers
sdnotify-proxy[2609]: I0717 12:26:17.686235 00001 main.go:141] Determining IP address of default interface
sdnotify-proxy[2609]: I0717 12:26:17.686910 00001 main.go:189] Using 10.0.23.47 as external interface
sdnotify-proxy[2609]: go-etcd2015/07/17 12:26:17 DEBUG: get /coreos.com/network/config [http://localhost:2379]
sdnotify-proxy[2609]: go-etcd2015/07/17 12:26:17 DEBUG: Connecting to etcd: attempt 1 for keys/coreos.com/network/config?quorum=false&recursive=false&sorted=false
sdnotify-proxy[2609]: go-etcd2015/07/17 12:26:17 DEBUG: send.request.to http://localhost:2379/v2/keys/coreos.com/network/config?quorum=false&recursive=false&sorted=false | method GET
sdnotify-proxy[2609]: go-etcd2015/07/17 12:26:17 DEBUG: recv.response.from
sdnotify-proxy[2609]: go-etcd2015/07/17 12:26:17 DEBUG: recv.success
sdnotify-proxy[2609]: go-etcd2015/07/17 12:26:17 DEBUG: get /coreos.com/network/config [http://localhost:2379]
sdnotify-proxy[2609]: go-etcd2015/07/17 12:26:17 DEBUG: Connecting to etcd: attempt 1 for keys/coreos.com/network/config?quorum=false&recursive=false&sorted=false
sdnotify-proxy[2609]: go-etcd2015/07/17 12:26:17 DEBUG: send.request.to http://localhost:2379/v2/keys/coreos.com/network/config?quorum=false&recursive=false&sorted=false | method GET
sdnotify-proxy[2609]: go-etcd2015/07/17 12:26:17 DEBUG: recv.response.from
sdnotify-proxy[2609]: go-etcd2015/07/17 12:26:17 DEBUG: recv.success
sdnotify-proxy[2609]: go-etcd2015/07/17 12:26:17 DEBUG: get /coreos.com/network/subnets [http://localhost:2379]
sdnotify-proxy[2609]: go-etcd2015/07/17 12:26:17 DEBUG: Connecting to etcd: attempt 1 for keys/coreos.com/network/subnets?quorum=false&recursive=true&sorted=false
sdnotify-proxy[2609]: go-etcd2015/07/17 12:26:17 DEBUG: send.request.to http://localhost:2379/v2/keys/coreos.com/network/subnets?quorum=false&recursive=true&sorted=false | method GET
sdnotify-proxy[2609]: go-etcd2015/07/17 12:26:17 DEBUG: recv.response.from
sdnotify-proxy[2609]: go-etcd2015/07/17 12:26:17 DEBUG: recv.success
sdnotify-proxy[2609]: I0717 12:26:17.694873 00001 etcd.go:136] Found lease (172.17.82.0/24) for current IP (10.0.23.47), reusing
sdnotify-proxy[2609]: go-etcd2015/07/17 12:26:17 DEBUG: put /coreos.com/network/subnets/172.17.82.0-24, {"PublicIP":"10.0.23.47"}, ttl: 86400, [http://localhost:2379]
sdnotify-proxy[2609]: go-etcd2015/07/17 12:26:17 DEBUG: Connecting to etcd: attempt 1 for keys/coreos.com/network/subnets/172.17.82.0-24
sdnotify-proxy[2609]: go-etcd2015/07/17 12:26:17 DEBUG: send.request.to http://localhost:2379/v2/keys/coreos.com/network/subnets/172.17.82.0-24 | method PUT
sdnotify-proxy[2609]: go-etcd2015/07/17 12:26:17 DEBUG: recv.response.from
sdnotify-proxy[2609]: go-etcd2015/07/17 12:26:17 DEBUG: recv.success
sdnotify-proxy[2609]: I0717 12:26:17.706881 00001 etcd.go:91] Subnet lease acquired: 172.17.82.0/24
sdnotify-proxy[2609]: I0717 12:26:17.981891 00001 awsvpc.go:110] RouteTableID not passed as config parameter, detecting ...
sdnotify-proxy[2609]: I0717 12:26:18.098653 00001 awsvpc.go:205] SubnetId: subnet-bfbeaccb
sdnotify-proxy[2609]: panic: runtime error: index out of range
sdnotify-proxy[2609]: goroutine 9 [running]:
sdnotify-proxy[2609]: github.com/coreos/flannel/backend/awsvpc.(*AwsVpcBackend).detectRouteTableID(0xc20800cc40, 0xc208029280, 0xa, 0xc2080a65a0, 0x0, 0x0)
sdnotify-proxy[2609]: /opt/flannel/gopath/src/github.com/coreos/flannel/backend/awsvpc/awsvpc.go:215 +0x726
sdnotify-proxy[2609]: github.com/coreos/flannel/backend/awsvpc.(*AwsVpcBackend).Init(0xc20800cc40, 0xc208038a80, 0xc208089070, 0x4, 0xf90, 0x0, 0x0, 0x0)
sdnotify-proxy[2609]: /opt/flannel/gopath/src/github.com/coreos/flannel/backend/awsvpc/awsvpc.go:111 +0xc69
sdnotify-proxy[2609]: github.com/coreos/flannel/network.func·003(0x0, 0x0)
sdnotify-proxy[2609]: /opt/flannel/gopath/src/github.com/coreos/flannel/network/network.go:69 +0x8c
sdnotify-proxy[2609]: github.com/coreos/flannel/network.(*Network).Init(0xc208038b00, 0x7f524f2b83b0, 0xc2080387c0, 0xc208038a80, 0xc208089070, 0x4, 0xf90, 0x0)
sdnotify-proxy[2609]: /opt/flannel/gopath/src/github.com/coreos/flannel/network/network.go:95 +0x53d
sdnotify-proxy[2609]: main.func·003(0xc208038b00)
sdnotify-proxy[2609]: /opt/flannel/gopath/src/github.com/coreos/flannel/main.go:203 +0xbd
sdnotify-proxy[2609]: created by main.initAndRun
sdnotify-proxy[2609]: /opt/flannel/gopath/src/github.com/coreos/flannel/main.go:220 +0x84b
sdnotify-proxy[2609]: goroutine 1 [chan receive]:
sdnotify-proxy[2609]: main.main()
sdnotify-proxy[2609]: /opt/flannel/gopath/src/github.com/coreos/flannel/main.go:288 +0xa2a
sdnotify-proxy[2609]: goroutine 5 [chan receive]:
sdnotify-proxy[2609]: github.com/coreos/flannel/Godeps/_workspace/src/github.com/golang/glog.(*loggingT).flushDaemon(0xd51200)
sdnotify-proxy[2609]: /opt/flannel/gopath/src/github.com/coreos/flannel/Godeps/_workspace/src/github.com/golang/glog/glog.go:839 +0x78
sdnotify-proxy[2609]: created by github.com/coreos/flannel/Godeps/_workspace/src/github.com/golang/glog.init·1
sdnotify-proxy[2609]: /opt/flannel/gopath/src/github.com/coreos/flannel/Godeps/_workspace/src/github.com/golang/glog/glog.go:406 +0x2a7
sdnotify-proxy[2609]: goroutine 17 [syscall, locked to thread]:
sdnotify-proxy[2609]: runtime.goexit()
sdnotify-proxy[2609]: /usr/src/go/src/runtime/asm_amd64.s:2232 +0x1
sdnotify-proxy[2609]: goroutine 6 [syscall]:
sdnotify-proxy[2609]: os/signal.loop()
sdnotify-proxy[2609]: /usr/src/go/src/os/signal/signal_unix.go:21 +0x1f
sdnotify-proxy[2609]: created by os/signal.init·1
sdnotify-proxy[2609]: /usr/src/go/src/os/signal/signal_unix.go:27 +0x35
sdnotify-proxy[2609]: goroutine 12 [IO wait]:
sdnotify-proxy[2609]: net.(*pollDesc).Wait(0xc20800c7d0, 0x72, 0x0, 0x0)
sdnotify-proxy[2609]: /usr/src/go/src/net/fd_poll_runtime.go:84 +0x47
sdnotify-proxy[2609]: net.(*pollDesc).WaitRead(0xc20800c7d0, 0x0, 0x0)
sdnotify-proxy[2609]: /usr/src/go/src/net/fd_poll_runtime.go:89 +0x43
sdnotify-proxy[2609]: net.(*netFD).Read(0xc20800c770, 0xc20808d000, 0x1000, 0x1000, 0x0, 0x7f524f2b7e68, 0xc208029050)
sdnotify-proxy[2609]: /usr/src/go/src/net/fd_unix.go:242 +0x40f
sdnotify-proxy[2609]: net.(*conn).Read(0xc20802a0c8, 0xc20808d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
sdnotify-proxy[2609]: /usr/src/go/src/net/net.go:121 +0xdc
sdnotify-proxy[2609]: net/http.noteEOFReader.Read(0x7f524f2b95e0, 0xc20802a0c8, 0xc208080268, 0xc20808d000, 0x1000, 0x1000, 0x7fdb40, 0x0, 0x0)
sdnotify-proxy[2609]: /usr/src/go/src/net/http/transport.go:1270 +0x6e
sdnotify-proxy[2609]: net/http.(*noteEOFReader).Read(0xc20800b220, 0xc20808d000, 0x1000, 0x1000, 0xc208010000, 0x0, 0x0)
sdnotify-proxy[2609]: <autogenerated>:125 +0xd4
sdnotify-proxy[2609]: bufio.(*Reader).fill(0xc20804c840)
sdnotify-proxy[2609]: /usr/src/go/src/bufio/bufio.go:97 +0x1ce
sdnotify-proxy[2609]: bufio.(*Reader).Peek(0xc20804c840, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
sdnotify-proxy[2609]: /usr/src/go/src/bufio/bufio.go:132 +0xf0
sdnotify-proxy[2609]: net/http.(*persistConn).readLoop(0xc208080210)
sdnotify-proxy[2609]: /usr/src/go/src/net/http/transport.go:842 +0xa4
sdnotify-proxy[2609]: created by net/http.(*Transport).dialConn
sdnotify-proxy[2609]: /usr/src/go/src/net/http/transport.go:660 +0xc9f
sdnotify-proxy[2609]: goroutine 13 [select]:
sdnotify-proxy[2609]: net/http.(*persistConn).writeLoop(0xc208080210)
sdnotify-proxy[2609]: /usr/src/go/src/net/http/transport.go:945 +0x41d
sdnotify-proxy[2609]: created by net/http.(*Transport).dialConn
sdnotify-proxy[2609]: /usr/src/go/src/net/http/transport.go:661 +0xcbc
sdnotify-proxy[2609]: goroutine 37 [runnable]:
sdnotify-proxy[2609]: net/http.(*persistConn).readLoop(0xc208080dc0)
sdnotify-proxy[2609]: /usr/src/go/src/net/http/transport.go:928 +0x9ce
sdnotify-proxy[2609]: created by net/http.(*Transport).dialConn
sdnotify-proxy[2609]: /usr/src/go/src/net/http/transport.go:660 +0xc9f
sdnotify-proxy[2609]: goroutine 38 [select]:
sdnotify-proxy[2609]: net/http.(*persistConn).writeLoop(0xc208080dc0)
sdnotify-proxy[2609]: /usr/src/go/src/net/http/transport.go:945 +0x41d
sdnotify-proxy[2609]: created by net/http.(*Transport).dialConn
sdnotify-proxy[2609]: /usr/src/go/src/net/http/transport.go:661 +0xcbc
systemd[1]: flanneld.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
systemd[1]: Failed to start Network fabric for containers.
systemd[1]: flanneld.service: Unit entered failed state.
systemd[1]: flanneld.service: Failed with result 'exit-code'.
```

Explicitly associating the subnet to a route table is enough to fix the issue.

### PR DESCRIPTION
**Pull request by MohdAhmad**
Check if the subnet is explicitly linked to a route table, if not, then
configure aws-vpc backend to use the main route table for the vpc.

Fixes #256

### CODE REVIEW

File: backend/awsvpc/awsvpc.go [hunk 1]
```diff
@@ -201,8 +201,19 @@ func (m *AwsVpcBackend) detectRouteTableID(instanceID string, ec2c *ec2.EC2) err
 		return fmt.Errorf("error getting instance info: %v", err)
 	}
 
+	if len(resp.Reservations) == 0 {
+		return fmt.Errorf("error no reservations found")
```
Comment (eyakubovich) [inline backend/awsvpc/awsvpc.go]: No need for word "error" here.

File: backend/awsvpc/awsvpc.go [hunk 2]
```diff
@@ -201,8 +201,19 @@ func (m *AwsVpcBackend) detectRouteTableID(instanceID string, ec2c *ec2.EC2) err
...
+	}
+
+	if len(resp.Reservations[0].Instances) == 0 {
+		return fmt.Errorf("error no matching instance found with id: %v", instanceID)
```
Comment (eyakubovich) [inline backend/awsvpc/awsvpc.go]: Same here, take our the word "error"

File: backend/awsvpc/awsvpc.go [hunk 3]
```diff
@@ -212,10 +223,28 @@ func (m *AwsVpcBackend) detectRouteTableID(instanceID string, ec2c *ec2.EC2) err
...
+	filter.Add("association.main", "true")
+	filter.Add("vpc-id", vpcID)
+
+	res, err = ec2c.DescribeRouteTables(nil, filter)
+	if err != nil {
+		log.Info("error describing route tables: ", err)
+	}
+
+	if len(res.RouteTables) == 0 {
+		return fmt.Errorf("error: main route table not found")
```
Comment (eyakubovich) [inline backend/awsvpc/awsvpc.go]: And here, take out "error: "

**Comment by eyakubovich** [comment]
LGTM except for few nits.
