### PR TITLE
backend/vxlan: simplify vxlan processing

### LINKED ISSUE #414: Errors in log using vxlan backend under CPU load
I have the following messages in the journal if cpu usage is > 60%

```
Mar 02 21:36:58 ip-10-0-2-240.eu-central-1.compute.internal sdnotify-proxy[2093]: E0302  21:36:58.118918 00001 device.go:218] Failed to receive from netlink: no buffer space available
Mar 02 21:36:59 ip-10-0-2-240.eu-central-1.compute.internal sdnotify-proxy[2093]: E0302  21:36:59.215630 00001 device.go:218] Failed to receive from netlink: no buffer space available
Mar 02 21:37:00 ip-10-0-2-240.eu-central-1.compute.internal sdnotify-proxy[2093]: E0302 21:37:00.316524 00001 device.go:218] Failed to receive from netlink: no buffer space available
Mar 02 21:37:01 ip-10-0-2-240.eu-central-1.compute.internal sdnotify-proxy[2093]: E0302 21:37:01.465853 00001 device.go:218] Failed to receive from netlink: no buffer space available
```

It goes from here
https://github.com/coreos/flannel/blob/7cb8d6b9a80632828e9569033d411361afee1816/backend/vxlan/device.go#L218

Do I need to tweak some parameters?

I have already played with

```
sudo sysctl -w net.ipv4.tcp_rmem="10240 87380 12582912"
sudo sysctl -w net.ipv4.tcp_wmem="10240 87380 12582912"

sudo sysctl -w net.ipv4.tcp_rmem="102400 873800 125829120"
sudo sysctl -w net.ipv4.tcp_wmem="102400 873800 125829120"

sudo sysctl -w net.core.wmem_max="125829120"
sudo sysctl -w net.core.rmem_max="125829120"

sudo sysctl -w net.ipv4.tcp_window_scaling="1"
sudo sysctl -w net.ipv4.tcp_timestamps="1"

sudo sysctl -w net.ipv4.tcp_sack="1"
sudo sysctl -w net.core.netdev_max_backlog="5000"

sudo sysctl -w net.ipv4.udp_mem="102400 873800 125829120"
sudo sysctl -w net.ipv4.udp_mem="102400 873800 125829120"

sudo sysctl -w net.ipv4.udp_rmem_min="10240"
sudo sysctl -w net.ipv4.udp_wmem_min="10240"

sudo sysctl -w net.core.rmem_default=524280
sudo sysctl -w net.core.rmem_max=524280
```

### LINKED ISSUE #427: L3 miss and Route not found loop
Hi there, 
I'm running Flannel v0.5.5 in vxlan mode as part of a Kubernetes cluster.  I seem to keep getting this repeating:

```
<Timestamp> <host> flanneld[873]: I0407 18:36:51.705743 00873 vxlan.go:345] L3 miss: <Service's IP>
<Timestamp> <host> flanneld[873]: I0407 18:36:51.705865 00873 vxlan.go:349] Route for <Service's IP> not found
```

It only happens to one node in the cluster at a time.  It would seem like it's not aware a route has changed/removed and it is still looking for it. 

It all was working fine for awhile, then I updated one service and then I keep getting this.

### LINKED ISSUE #592: Flannel.1 drop packets regularly in a 80 nodes cluster
Hi,

We deployed flannel version0.5.5 in our productive env. however, we found the flannel.1 interface drop packets regularly. we looked the flannel log file and also dig into the vxlan kernel module, but have not found any strong raison.

Right now, I am only suspending that the FDB table in flannel.1 expired after some time, the flannel.1 then has no idea where to send the packet, then drop it. and as the fdb is watched from etcd, there may be a delay to update the fdb table. 

thank you very much for any advice for our problem

cc @keontang @mqliang

### LINKED ISSUE #604: centos flannel vxlan, ping cross host failed
I have tried udp as backend and there is no problem, but when I use vxlan, I can not ping cross host.

**what I have read:**

- #216 
- #370 
- #111 
- #415 
- #87 
- #481 

**linux info:** CentOS release 6.8 (Final)

**kernnel version:** 2.6.32-573.22.1.el6.x86_64

**docker version:** 1.7.1

**vxlan support:**
```bash
$ sudo modprobe vxlan && echo $?
0

$ ip link add type vxlan help
Usage: ... vxlan id VNI [ group ADDR ] [ local ADDR ]
                 [ ttl TTL ] [ tos TOS ] [ dev PHYS_DEV ]
                 [ port MIN MAX ] [ [no]learning ]
                 [ [no]proxy ] [ [no]rsc ]
                 [ [no]l2miss ] [ [no]l3miss ]

Where: VNI := 0-16777215
       ADDR := { IP_ADDRESS | any }
       TOS  := { NUMBER | inherit }
       TTL  := { 1..255 | inherit }
```
sames support vxlan

**etcd version:** 
```bash
$ etcd --version
etcd Version: 3.0.16
Git SHA: a23109a
Go Version: go1.6.4
Go OS/Arch: linux/amd64
```

**flanneld version:** v0.7.0

**route:**
172.17.0.0      *               255.255.0.0     U     0      0        0 flannel.1

**flannel config:**
```json
{ "Network": "172.17.0.0/16", "SubnetLen": 24, "Backend": { "Type": "vxlan", "VNI": 1, "Port": 8472 }}
```

**port:**
e5d04aaf-6f4e-44e4-9574-316bd8a8b7d7

**subnet info:**
/coreos.com/network/subnets/172.17.49.0-24
/coreos.com/network/subnets/172.17.70.0-24
/coreos.com/network/subnets/172.17.63.0-24

**flannel log:**
c2350510-1416-479c-aeb2-dcc9aba0742e

It sames that **adding subnet not done**, but there is no error info and ping failed cross host. What's the right output when add subnet succeeds? 

**ping:**
98a3609a-bac1-47f6-903f-455e022f6a71

```bash
arp -v 
172.17.49.0                      (incomplete)                              flannel.1
```

What should I do? Is there any way to fix or debug this problem? Thank you!

### LINKED ISSUE #617: vxlan mode not work on centos6 ?
I have 2 server one is Centos6.7 and the other is Centos7.2
I installed flannel on them and then create the net bridge.
But only centos7 works well, CentOS6 can't access any other hosts when using flannel network

````bash
ping 172.30.57.1
connect: Invalid argument
````

* create net bridge
````bash
brctl addbr cbr0
ip addr add ${FLANNEL_SUBNET}/24 dev cbr0
ip link set dev cbr0 mtu 1450
ip link set dev cbr0 up
````

*  Flannel config on etcd
````bash
set /coreos.com/network/config “{\”Network\”:\”172.30.0.0/16\”,\”Backend\”:{\”Type\”:\”vxlan\”}}”
````

* OS infomation on Centos6
````bash
# ifconfig
cbr0      Link encap:Ethernet  HWaddr EE:1F:7B:36:8F:5E  
          inet addr:172.30.67.1  Bcast:0.0.0.0  Mask:255.255.255.0
          inet6 addr: fe80::ec1f:7bff:fe36:8f5e/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1450  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:6 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 b)  TX bytes:468 (468.0 b)

eth0      Link encap:Ethernet  HWaddr 00:0C:29:A0:E1:4E  
          inet addr:192.168.198.125  Bcast:192.168.198.255  Mask:255.255.255.0
          inet6 addr: fe80::20c:29ff:fea0:e14e/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:266319 errors:0 dropped:0 overruns:0 frame:0
          TX packets:68169 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:300655060 (286.7 MiB)  TX bytes:8129566 (7.7 MiB)

flannel.1 Link encap:Ethernet  HWaddr EE:9A:AC:AF:B3:6B  
          inet addr:172.30.67.0  Bcast:0.0.0.0  Mask:255.255.255.255
          inet6 addr: fe80::ec9a:acff:feaf:b36b/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1450  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:96 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 b)  TX bytes:0 (0.0 b)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:105 errors:0 dropped:0 overruns:0 frame:0
          TX packets:105 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:11256 (10.9 KiB)  TX bytes:11256 (10.9 KiB)

# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
172.30.67.0     0.0.0.0         255.255.255.0   U     0      0        0 cbr0
192.168.198.0   0.0.0.0         255.255.255.0   U     0      0        0 eth0
172.30.0.0      0.0.0.0         255.255.0.0     U     0      0        0 flannel.1
169.254.0.0     0.0.0.0         255.255.0.0     U     1002   0        0 eth0
0.0.0.0         192.168.198.2   0.0.0.0         UG    0      0        0 eth0

# cat /var/log/flanneld.log
I0222 23:48:01.388762   36691 main.go:132] Installing signal handlers
I0222 23:48:01.388916   36691 manager.go:136] Determining IP address of default interface
I0222 23:48:01.389745   36691 manager.go:149] Using interface with name eth0 and address 192.168.198.125
I0222 23:48:01.389779   36691 manager.go:166] Defaulting external address to interface address (192.168.198.125)
I0222 23:48:01.433709   36691 local_manager.go:134] Found lease (172.30.67.0/24) for current IP (192.168.198.125), reusing
I0222 23:48:01.439959   36691 ipmasq.go:47] Adding iptables rule: -s 172.30.0.0/16 -d 172.30.0.0/16 -j RETURN
I0222 23:48:01.442605   36691 ipmasq.go:47] Adding iptables rule: -s 172.30.0.0/16 ! -d 224.0.0.0/4 -j MASQUERADE
I0222 23:48:01.483603   36691 ipmasq.go:47] Adding iptables rule: ! -s 172.30.0.0/16 -d 172.30.0.0/16 -j MASQUERADE
I0222 23:48:01.487269   36691 manager.go:250] Lease acquired: 172.30.67.0/24
I0222 23:48:01.488181   36691 network.go:58] Watching for L3 misses
I0222 23:48:01.488198   36691 network.go:66] Watching for new subnet leases

# iptables-save
# Generated by iptables-save v1.4.7 on Wed Feb 22 23:53:24 2017
*nat
:PREROUTING ACCEPT [0:0]
:POSTROUTING ACCEPT [4:258]
:OUTPUT ACCEPT [4:258]
-A POSTROUTING -s 172.30.0.0/16 -d 172.30.0.0/16 -j RETURN 
-A POSTROUTING -s 172.30.0.0/16 ! -d 224.0.0.0/4 -j MASQUERADE 
-A POSTROUTING ! -s 172.30.0.0/16 -d 172.30.0.0/16 -j MASQUERADE 
COMMIT
# Completed on Wed Feb 22 23:53:24 2017
# Generated by iptables-save v1.4.7 on Wed Feb 22 23:53:24 2017
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [420:70389]
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT 
-A INPUT -p icmp -j ACCEPT 
-A INPUT -i lo -j ACCEPT 
-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT 
-A INPUT -j REJECT --reject-with icmp-host-prohibited 
-A FORWARD -j REJECT --reject-with icmp-host-prohibited 
COMMIT
# Completed on Wed Feb 22 23:53:24 2017
````

flannel version: 0.7.0
OS version: Centos6.7

### LINKED ISSUE #654: Solve a cannot ping problem
We have a k8s cluster of 50 nodes using flannel. We are using flannel(0.5.5) with wxlan backend. Now we meet a network problem: some of nodes can not ping each other's flannel IP, but these nodes can ping other nodes. Something like this:
> A <--x--> B .         A and B can not ping each other's flannel IP.
> A <-----> C .         But both A and B can ping C' s flannel IP, And C also can ping A and B.
> B <-----> C

There are about 100 unreachable chains in this cluster. But we don't meet this problem in a smaller cluster.

We are using CentOS 7.2, kernel is 4.4.29-1.el7.elrepo.x86_64. All the servers are a virtual machines created in Openstack. The docker info is followed.

>[xxxx@xxxx ~]$ docker info
>Containers: 34
> Running: 32
> Paused: 0
> Stopped: 2
>Images: 50
> Server Version: 1.10.3
> Storage Driver: overlay
>  Backing Filesystem: extfs
> Execution Driver: native-0.2
> Logging Driver: json-file
> Plugins:
>  Volume: local
>  Network: null host bridge
> Kernel Version: 4.4.29-1.el7.elrepo.x86_64
> Operating System: CentOS Linux 7 (Core)
> OSType: linux
> Architecture: x86_64
> CPUs: 8
> Total Memory: 15.67 GiB
> Name: xxxxxx
>ID: XXXX:XXXX:XXXX:WRT3:FADD:GGZO:AO7P:Y3KL:XXXX:XXXX:XXXX:XXXX
>WARNING: bridge-nf-call-ip6tables is disabled

After data capturing and analysis,  I found the cause is the bridge's fdb table has lost the entries of unreachable nodes. 

I used "bridge fdb show" to list all fdb entries, and I found the unreachable node's entries is missed. 

>[xxxx@xxxx ~]bridge fdb show
>xx:xx:xx:57:27:d8 dev flannel.1 dst 192.168.110.89 self permanent
>xx:xx:xx:64:26:2f dev flannel.1 dst 192.168.110.86 self permanent
>xx:xx:xx:25:6e:65 dev flannel.1 dst 192.168.110.82 self permanent
>……

So, I use 'bridge' command to add the lost entry, but get this error: "RTNETLINK answers: File exists".

>[xxxx@xxxx ~]$ sudo bridge fdb add xx:xx:xx:cc:dd:a7 dev flannel.1 dst 192.168.110.18 self permanent
>RTNETLINK answers: File exists

It seems some existing file prevented from adding fdb entry. So, I do the "del" first and then add it again. This time, it works fine.

>[xxxx@xxxx ~]$ sudo bridge fdb del xx:xx:xx:cc:dd:a7 dev flannel.1
>[xxxx@xxxx ~]$ sudo bridge fdb add xx:xx:xx:cc:dd:a7 dev flannel.1 dst 192.168.110.18 self permanent

After I make this fix on both side of unreachable nodes. They can ping each other.

I don't know why the fdb entry will lost. And I checked the flannel's source code, I found the flannel do AddL2 by calling netlink.NeighAdd(). And in the netlink's source code, I found it use a syscall RTM_NEWNEIGH to do this work. I think the flannel may meet the same "File exists" problem when it execute AddL2 on the fdb entry lost condition . To make better, Is it possible that call NeighDel() first before AddL2()? Just like what I do by bridge command. I'm not sure if this is reasonable. I'm not good at linux network.

Any comments?

### LINKED ISSUE #779: Excessive "Failed to receive from netlink: no buffer space available" errors
We run `flannel` for our Kubernetes clusters, but not as a CNI plugin yet. Still the old way - run `flannel`, output the properties file, let `docker` read `--bip` flag from the properties file. 

We noticed a large amount of the following errors when the cluster is under load:
```
Jul 14 15:11:46 ip-10-72-134-42.ec2.internal flannel-wrapper[1528]: E0714 15:11:46.419175    1528 device.go:222] Failed to receive from netlink: no buffer space available"
```

## Expected Behavior

We should see fewer errors in `flannel` logs?

## Current Behavior

We see _a lot_ of such errors. Below is a Kibana screenshot.

screen shot 2017-07-14 at 7 49 08 pm

## Steps to Reproduce (for bugs)

1. Scale Kubernetes cluster to ~300 minions.
2. Increase load/traffic on the cluster
3. Check `flannel` logs.

## Context
We are seeing network timeouts in almost all of our microservices in the cluster, not sure if they are related, but highly susceptible.

## Your Environment

* Flannel version: v0.7.0
* Backend used (e.g. vxlan or udp): vxlan
* Etcd version: v3.1.9
* Kubernetes version (if used): v1.5.7
* Operating System and version: CoreOS 1353.7.0 stable
* Link to your project (optional):

### PR DESCRIPTION
**Pull request by tomdee**
No need for any netlink monitoring anymore
This means vxlan should work with older kernels (Centos 6)
and it should perform betteron heavily loaded systems.

This change is compatible with older versions of flannel 
so it should be OK to do rolling upgrades to it.

Some notes on how vxlan worked before and how this changes it can be found in the code https://github.com/coreos/flannel/pull/785/files#diff-2fcdad83a560522bb17d06e480b6ed76R17

Fixes #779 
Fixes #592 
Fixes #617 
Fixes #654 
Fixes #604 
Fixes #414 
Fixes #427

### CODE REVIEW

**Comment by ayaz** [comment]
@tomdee @gunjan5 When can we hope to have this available officially? I have just had this bug hit me on a perfectly running cluster.

**Comment by gunjan5** [comment]
@ayaz I plan to review it in the next few days, then it will need some testing before it's merged into master

File: backend/vxlan/device.go [hunk 1]
```diff
@@ -160,14 +151,9 @@ type neighbor struct {
...
 
-func (dev *vxlanDevice) GetL2List() ([]netlink.Neigh, error) {
-	log.V(4).Infof("calling GetL2List() dev.link.Index: %d ", dev.link.Index)
-	return netlink.NeighList(dev.link.Index, syscall.AF_BRIDGE)
-}
-
-func (dev *vxlanDevice) AddL2(n neighbor) error {
-	log.V(4).Infof("calling NeighAdd: %v, %v", n.IP, n.MAC)
-	return netlink.NeighAdd(&netlink.Neigh{
+func (dev *vxlanDevice) AddFdb(n neighbor) error {
```
Comment (gunjan5) [inline backend/vxlan/device.go]: I think a better name would be `AddFDB` since FDB is an acronym
See: https://github.com/golang/go/wiki/CodeReviewComments#initialisms (also applies to a bunch of other method names in this file.)

File: backend/vxlan/device.go [hunk 2]
```diff
@@ -177,8 +163,8 @@ func (dev *vxlanDevice) AddL2(n neighbor) error {
 	})
 }
 
-func (dev *vxlanDevice) DelL2(n neighbor) error {
-	log.V(4).Infof("calling NeighDel: %v, %v", n.IP, n.MAC)
+func (dev *vxlanDevice) DelFdb(n neighbor) error {
```
Comment (gunjan5) [inline backend/vxlan/device.go]: Same here, a better name would be `DelFDB`

File: backend/vxlan/device.go [hunk 3]
```diff
@@ -188,77 +174,28 @@ func (dev *vxlanDevice) DelL2(n neighbor) error {
 	})
 }
 
-func (dev *vxlanDevice) AddL3(n neighbor) error {
-	log.V(4).Infof("calling NeighSet: %v, %v", n.IP, n.MAC)
+func (dev *vxlanDevice) AddArp(n neighbor) error {
```
Comment (gunjan5) [inline backend/vxlan/device.go]: a better name would be `AddARP`

File: backend/vxlan/vxlan_network.go [hunk 4]
```diff
@@ -111,140 +85,59 @@ type vxlanLeaseAttrs struct {
...
+			if err := netlink.RouteDel(&route); err != nil {
+				log.Errorf("failed to delete route (%s -> %s): %v", route.Dst, route.Gw, err)
+			}
 
-	if err := nw.dev.AddL3(neighbor{IP: ip.FromIP(miss.IP), MAC: route.vtepMAC}); err != nil {
-		log.Errorf("AddL3 failed: %v", err)
-	} else {
-		log.V(2).Infof("L3 miss: AddL3 for %s succeeded", miss.IP)
+		default:
+			log.Error("Internal error: unknown event type: ", int(event.Type))
```
Comment (gunjan5) [inline backend/vxlan/vxlan_network.go]: any reason why you have some error logs with `log.Error` and uppercase error message vs `log.Errorf` and a lowercase message?

File: backend/vxlan/vxlan_network.go [hunk 5]
```diff
@@ -111,140 +85,59 @@ type vxlanLeaseAttrs struct {
...
 
-		// Store off the subnet lease and VTEP
-		nw.routes.set(evt.Lease.Subnet, net.HardwareAddr(leaseAttrsList[eventMarkerIndex].VtepMAC))
-		log.V(2).Infof("Adding subnet: %s PublicIP: %s VtepMAC: %s", evt.Lease.Subnet, evt.Lease.Attrs.PublicIP, net.HardwareAddr(leaseAttrsList[eventMarkerIndex].VtepMAC))
-	}
+		switch event.Type {
+		case subnet.EventAdded:
+			log.V(2).Infof("Adding subnet: %s PublicIP: %s VtepMAC: %s", event.Lease.Subnet, event.Lease.Attrs.PublicIP, net.HardwareAddr(attrs.VtepMAC))
+			if err := nw.dev.AddArp(neighbor{IP: event.Lease.Subnet.IP, MAC: net.HardwareAddr(attrs.VtepMAC)}); err != nil {
+				log.Error("AddArp failed: ", err)
```
Comment (tomdee) [inline backend/vxlan/vxlan_network.go]: Returning would just mean that we don't try to process the rest of the events in the batch. I think it's still worth trying to process those events. What's your reasoning for why we shouldn't try?

File: backend/vxlan/vxlan_network.go [hunk 6]
```diff
@@ -111,140 +85,59 @@ type vxlanLeaseAttrs struct {
...
+			}
 
-	// Loop over the existing FDB entries, deleting any that shouldn't be there
-	for j, marker := range fdbEntryMarker {
-		if !marker && fdbTable[j].IP != nil {
-			err := nw.dev.DelL2(neighbor{IP: ip.FromIP(fdbTable[j].IP), MAC: fdbTable[j].HardwareAddr})
-			if err != nil {
-				log.Error("Delete L2 failed: ", err)
+			if err := nw.dev.AddFdb(neighbor{IP: event.Lease.Attrs.PublicIP, MAC: net.HardwareAddr(attrs.VtepMAC)}); err != nil {
+				log.Error("AddFdb failed: ", err)
```
Comment (tomdee) [inline backend/vxlan/vxlan_network.go]: gotcha, I thing maybe you're suggesting a "continue" rather than "return"? And advocating for cleaning up the failed FDB or arp entries? It sounds like a reasonable suggestion to me (though I don't think it really brings much benefit to the user and increases the code complexity).

File: backend/vxlan/vxlan_network.go (hunk 4 above)
Comment (tomdee) [inline backend/vxlan/vxlan_network.go]: I'll update them all to lowercase

File: backend/vxlan/device.go (hunk 1 above)
Comment (tomdee) [inline backend/vxlan/device.go]: Fixed

File: backend/vxlan/vxlan_network.go (hunk 6 above)
Comment (tomdee) [inline backend/vxlan/vxlan_network.go]: OK, I've addressed this now.

**Comment by tomdee** [comment]
@gunjan5 I've made markups (https://github.com/coreos/flannel/pull/785/commits/ea2cb640318af2bb3636b692d7aaff5365ddf4af) to address all your comments, PTAL.

**Comment by gunjan5** [comment]
@tomdee LGTM! I haven't had a chance to manually test this. I'm assuming you have done some testing? lmk if you want me to do some manual testing before the merge. I will likely not have any time this week tho

**Comment by tomdee** [comment]
I have done some testing, but I would love for people to do more testing before this gets released.

You can try it by using the image `quay.io/coreos/flannel-git:v0.8.0-14-g4973e02e`
