### PR TITLE
tests: fix bug due to random numbers being used

### LINKED ISSUE #381: Race in tests
There seems to be a race in tests that causes it to sometimes hang. Not sure if it's Go 1.5 specific or not:

```
Running tests...
ok  	github.com/coreos/flannel/pkg/ip	0.004s	coverage: 25.2% of statements
SIGQUIT: quit
PC=0x45ffb1 m=0
goroutine 0 [idle]:
runtime.futex(0x99e110, 0x0, 0x0, 0x0, 0x0, 0x99d720, 0x0, 0x0, 0x40f064, 0x99e110, ...)
	/usr/local/go/src/runtime/sys_linux_amd64.s:288 +0x21
runtime.futexsleep(0x99e110, 0x0, 0xffffffffffffffff)
	/usr/local/go/src/runtime/os1_linux.go:39 +0x53
runtime.notesleep(0x99e110)
	/usr/local/go/src/runtime/lock_futex.go:142 +0xa4
runtime.stopm()
	/usr/local/go/src/runtime/proc1.go:1128 +0x112
runtime.findrunnable(0xc820022000, 0x0)
	/usr/local/go/src/runtime/proc1.go:1530 +0x69e
runtime.schedule()
	/usr/local/go/src/runtime/proc1.go:1639 +0x267
runtime.park_m(0xc820001500)
	/usr/local/go/src/runtime/proc1.go:1698 +0x18b
runtime.mcall(0x7fff20ab4200)
	/usr/local/go/src/runtime/asm_amd64.s:204 +0x5b
goroutine 1 [chan receive]:
testing.RunTests(0x86ff70, 0x999920, 0xe, 0xe, 0xc8200aa401)
	/usr/local/go/src/testing/testing.go:562 +0x8ad
testing.(*M).Run(0xc82004fef8, 0x99d340)
	/usr/local/go/src/testing/testing.go:494 +0x70
main.main()
	github.com/coreos/flannel/subnet/_test/_testmain.go:142 +0x252
goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1
goroutine 5 [runnable]:
github.com/coreos/flannel/Godeps/_workspace/src/github.com/golang/glog.(*loggingT).flushDaemon(0x99d660)
	/home/travis/gopath/src/github.com/coreos/flannel/gopath/src/github.com/coreos/flannel/Godeps/_workspace/src/github.com/golang/glog/glog.go:839 +0x67
created by github.com/coreos/flannel/Godeps/_workspace/src/github.com/golang/glog.init.1
	/home/travis/gopath/src/github.com/coreos/flannel/gopath/src/github.com/coreos/flannel/Godeps/_workspace/src/github.com/golang/glog/glog.go:406 +0x297
goroutine 10 [chan receive]:
github.com/coreos/flannel/subnet.TestWatchLeaseAdded(0xc82001c480)
	/home/travis/gopath/src/github.com/coreos/flannel/gopath/src/github.com/coreos/flannel/subnet/subnet_test.go:162 +0x61e
testing.tRunner(0xc82001c480, 0x999980)
	/usr/local/go/src/testing/testing.go:456 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:561 +0x86d
goroutine 11 [select]:
github.com/coreos/flannel/subnet.(*MockSubnetRegistry).watchSubnets(0xc820014ee0, 0x7fbb8b95deb8, 0xc820010ec0, 0x7d0718, 0x1, 0x3e9, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/coreos/flannel/subnet/_test/_obj_test/mock_registry.go:289 +0x584
github.com/coreos/flannel/subnet.(*LocalManager).WatchLeases(0xc820188200, 0x7fbb8b95deb8, 0xc820010ec0, 0x7d0718, 0x1, 0x770400, 0xc8201883b0, 0x0, 0x0, 0x0, ...)
	github.com/coreos/flannel/subnet/_test/_obj_test/local_manager.go:365 +0x38e
github.com/coreos/flannel/subnet.WatchLeases(0x7fbb8b95deb8, 0xc820010ec0, 0x7fbb8b95db20, 0xc820188200, 0x7d0718, 0x1, 0xc82001ad20, 0xc82001ad80)
	github.com/coreos/flannel/subnet/_test/_obj_test/watch.go:39 +0x110
created by github.com/coreos/flannel/subnet.TestWatchLeaseAdded
	/home/travis/gopath/src/github.com/coreos/flannel/gopath/src/github.com/coreos/flannel/subnet/subnet_test.go:144 +0x2fc
rax    0xca
rbx    0x0
rcx    0xffffffffffffffff
rdx    0x0
rdi    0x99e110
rsi    0x0
rbp    0x1
rsp    0x7fff20ab4058
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0x1
r13    0x86d331
r14    0xa
r15    0x8
rip    0x45ffb1
rflags 0x286
cs     0x33
fs     0x0
gs     0x0
*** Test killed with quit: ran too long (10m0s).
FAIL	github.com/coreos/flannel/subnet	600.006s
?   	github.com/coreos/flannel/network	[no test files]
ok  	github.com/coreos/flannel/remote	1.520s	coverage: 58.7% of statements
The command "./test" exited with 1.
Done. Your build exited with 1.
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated
```

### PR DESCRIPTION
**Pull request by eyakubovich**
When using hard coded subnet values in tests,
it's important that they don't accidently end
up being the same as acquired leases.
Use SubnetMin/SubnetMax in config to segrate
hard coded and dynamically allocatable ranges.

Fixes #381

### CODE REVIEW

File: subnet/subnet_test.go [hunk 1]
```diff
@@ -39,6 +39,7 @@ func newDummyRegistry() *MockSubnetRegistry {
 		{ip.IP4Net{ip.MustParseIP4("10.3.2.0"), 24}, attrs, exp, 11},
 		{ip.IP4Net{ip.MustParseIP4("10.3.4.0"), 24}, attrs, exp, 12},
 		{ip.IP4Net{ip.MustParseIP4("10.3.5.0"), 24}, attrs, exp, 13},
+		{ip.IP4Net{ip.MustParseIP4("10.3.31.0"), 24}, attrs, exp, 13},
```
Comment (xiang90) [inline subnet/subnet_test.go]: can we add a comment for why 10.3.31.0 is here?

For example: a hand created lease outside the range of subnetMin-SubnetMax for testing removal.

**Comment by xiang90** [comment]
LGTM
